# Generated by Django 4.2.11 on 2026-06-07 14:51

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_diningtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningtable',
            name='qr_token',
            field=models.SlugField(default=restaurants.models.generate_qr_token, editable=False, max_length=64, unique=True),
        ),
    ]
