# Generated by Django 4.2.11 on 2026-06-10 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_diningtable_qr_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAppearanceTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#1B4332', max_length=7)),
                ('secondary_color', models.CharField(default='#D8F3DC', max_length=7)),
                ('accent_color', models.CharField(default='#E07A5F', max_length=7)),
                ('background_color', models.CharField(default='#F7F5F2', max_length=7)),
                ('text_color', models.CharField(default='#1F2933', max_length=7)),
                ('card_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('font_family', models.CharField(default='Plus Jakarta Sans', max_length=80)),
                ('layout_style', models.CharField(choices=[('grid', 'Grid nyaman'), ('compact', 'Compact'), ('featured', 'Featured')], default='grid', max_length=20)),
                ('header_style', models.CharField(choices=[('rounded', 'Rounded'), ('minimal', 'Minimal'), ('hero', 'Hero')], default='rounded', max_length=20)),
                ('button_style', models.CharField(choices=[('rounded', 'Rounded'), ('pill', 'Pill'), ('square', 'Square')], default='rounded', max_length=20)),
                ('show_category_tabs', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_theme', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Menu appearance theme',
                'verbose_name_plural': 'Menu appearance themes',
            },
        ),
    ]
