# Generated by Django 4.2.11 on 2026-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_menuappearancetheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuappearancetheme',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner tampilan customer (opsional).', null=True, upload_to='restaurants/banners/'),
        ),
        migrations.AddField(
            model_name='menuappearancetheme',
            name='contact_instagram',
            field=models.CharField(blank=True, help_text='Username Instagram (opsional).', max_length=80),
        ),
        migrations.AddField(
            model_name='menuappearancetheme',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Nomor telepon yang tampil untuk pelanggan.', max_length=30),
        ),
        migrations.AddField(
            model_name='menuappearancetheme',
            name='greeting_message',
            field=models.CharField(blank=True, help_text='Pesan sambutan untuk pelanggan.', max_length=300),
        ),
        migrations.AddField(
            model_name='menuappearancetheme',
            name='receipt_footer_text',
            field=models.CharField(blank=True, default='Terima kasih atas kunjungan Anda', help_text='Teks penutup pada struk (receipt).', max_length=200),
        ),
        migrations.AddField(
            model_name='menuappearancetheme',
            name='tagline',
            field=models.CharField(blank=True, help_text='Tagline / slogan singkat resto.', max_length=200),
        ),
    ]
