# Generated by Django 4.2.11 on 2026-08-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_menuappearancetheme_banner_image_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('dummy', 'Dummy (Simulasi)'), ('midtrans', 'Midtrans')], default='dummy', max_length=20)),
                ('midtrans_server_key_encrypted', models.TextField(blank=True, default='')),
                ('midtrans_client_key_encrypted', models.TextField(blank=True, default='')),
                ('midtrans_is_production', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Nonaktifkan tanpa menghapus key.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant payment config',
                'verbose_name_plural': 'Restaurant payment configs',
            },
        ),
    ]
