# Generated by Django 4.2.11 on 2026-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Diskon dalam persen (0-100)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah stok (0 = tanpa batas)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tax',
            field=models.PositiveSmallIntegerField(default=10, help_text='Pajak/PPN dalam persen'),
        ),
    ]
