# Generated by Django 4.2.11 on 2026-06-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_add_discount_tax_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemVariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama grup varian, contoh: Level Pedas', max_length=100)),
                ('type', models.CharField(choices=[('radio', 'Pilih Satu (Wajib)'), ('checkbox', 'Pilih Banyak (Opsional)')], default='radio', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_groups', to='menus.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama opsi, contoh: Pedas', max_length=100)),
                ('price_adjustment', models.IntegerField(default=0, help_text='Penyesuaian harga dalam Rupiah (positif = tambah, negatif = kurang)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menus.menuitemvariantgroup')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
