# Generated by Django 4.2.11 on 2026-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_add_variant_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Label menu favorit'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Label menu baru'),
        ),
    ]
