# Generated by Django 4.2.11 on 2026-08-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Pesanan Baru'), ('paid', 'Dibayar'), ('processing', 'Diproses'), ('ready', 'Siap Disajikan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='new', max_length=20),
        ),
    ]
